"""emu-atlas — the map of where emulators keep things.

A resolver, not a lookup: for any emulator installation on a machine, atlas
answers which configs govern it and where saves and BIOS actually live — by
reading the running machine the way the emulator does. Phase 1 covers RetroArch
across the RetroDECK, EmuDeck, standalone-Flatpak, and native install flavors,
plus firmware.

Two entry points, per DESIGN.md:

- :func:`atlas.detect` finds what is installed and returns installation handles;
- every question is asked of a handle —
  ``installation.save_location(content_path=..., core_so=...)``,
  ``installation.firmware_status(platform=...)``.
"""

from __future__ import annotations

from atlas.contract import (
    emulator_contract,
    firmware_contract,
    installation_contract,
    placement_contract,
    unresolved_contract,
)
from atlas.core_info import parse_core_info
from atlas.firmware import (
    CAVEAT_CORE_DIR_UNRESOLVED,
    CAVEAT_FIRMWARE_ROOT_MISSING,
    CAVEAT_INFO_PATH_UNRESOLVED,
    CAVEAT_NO_FIRMWARE_DECLARATION,
    STATE_MISMATCH,
    STATE_MISSING,
    STATE_PRESENT,
    STATE_UNDECLARED,
    STATE_VERIFIED,
    FirmwareDeclaration,
    FirmwareFile,
    FirmwareHash,
    FirmwareHashes,
    FirmwareReport,
    FirmwareState,
    load_hashes,
    read_declarations,
    resolve_firmware,
)
from atlas.detect import detect
from atlas.esde import KIND_LIBRETRO, KIND_STANDALONE, EmulatorSpec, GamelistSelections, parse_es_systems, parse_gamelist, parse_gamelist_alternative
from atlas.installations import (
    HEALTH_ISSUE_COMPANION_CONFIG_MISSING,
    HEALTH_ISSUE_CONFIG_UNREADABLE,
    HEALTH_ISSUE_MARKER_INVALID,
    HEALTH_ISSUE_MARKER_MISSING,
    HEALTH_ISSUE_MARKER_UNREADABLE,
    HEALTH_ISSUE_ROOT_MISSING,
    HEALTH_ISSUE_SAVES_ROOT_MISSING,
    EmuDeck,
    EmulatorEntry,
    Health,
    Installation,
    NativeRetroArch,
    RetroDeck,
    StandaloneRetroArchFlatpak,
)
from atlas.machine import CoreInfo, CoreOption, FixtureMachine, Machine, RealMachine
from atlas.oddities import (
    AuditEntry,
    CoreCard,
    SaveMode,
    VerifiedOn,
    load_audit,
    load_oddities,
    lookup_audit,
    lookup_card,
)
from atlas.placement import (
    CAVEAT_CORE_UNQUERYABLE,
    CAVEAT_FILENAMES_UNVERIFIED,
    CAVEAT_HEALTH,
    CAVEAT_NO_CORE,
    CAVEAT_SORTED_DIR_MISSING,
    CAVEAT_PER_GAME_OVERRIDE,
    CAVEAT_PER_GAME_OVERRIDES_PRESENT,
    CAVEAT_SYSTEM_DIR_UNSET,
    CAVEAT_UNKNOWN_OPTION_VALUE,
    CAVEAT_UNVERIFIED_VERSION,
    CAVEAT_CARD_GENERATION_MISMATCH,
    CAVEAT_CARD_MODE_UNCONFIRMED,
    CAVEAT_CORE_SUSPECT,
    CAVEAT_CORE_UNAUDITED,
    CAVEAT_DEAD_SYMLINK,
    CAVEAT_INVALID_SAVE_DIRECTORY,
    CAVEAT_SORTED_DIR_UNCREATABLE,
    ROOT_CONTENT_DIRECTORY,
    ROOT_SAVEFILE_DIRECTORY,
    ROOT_SYSTEM_DIRECTORY,
    UNKNOWN_FILE_SET,
    UNRESOLVED_STANDALONE,
    Caveat,
    FileSet,
    Granularity,
    SavePlacement,
    Unresolved,
    build_save_placement,
)
from atlas.retroarch_cfg import (
    EMUDECK_DEFAULTS,
    RETRODECK_DEFAULTS,
    UPSTREAM_DEFAULTS,
    LayoutDefaults,
    RetroArchCfg,
    interpret_cfg,
    parse_cfg_text,
    resolve_save_layout,
)

__all__ = [
    "parse_es_systems",
    "lookup_card",
    "lookup_audit",
    "load_oddities",
    "load_audit",
    "VerifiedOn",
    "SaveMode",
    "Granularity",
    "GamelistSelections",
    "CoreCard",
    "AuditEntry",
    "CAVEAT_DEAD_SYMLINK",
    "CAVEAT_INVALID_SAVE_DIRECTORY",
    "CAVEAT_CORE_UNAUDITED",
    "CAVEAT_CORE_SUSPECT",
    "CAVEAT_CARD_GENERATION_MISMATCH",
    "CAVEAT_CARD_MODE_UNCONFIRMED",
    "CAVEAT_SORTED_DIR_UNCREATABLE",
    "CAVEAT_CORE_UNQUERYABLE",
    "CAVEAT_FILENAMES_UNVERIFIED",
    "CAVEAT_HEALTH",
    "CAVEAT_NO_CORE",
    "CAVEAT_SORTED_DIR_MISSING",
    "CAVEAT_PER_GAME_OVERRIDE",
    "CAVEAT_PER_GAME_OVERRIDES_PRESENT",
    "CAVEAT_SYSTEM_DIR_UNSET",
    "CAVEAT_UNKNOWN_OPTION_VALUE",
    "CAVEAT_UNVERIFIED_VERSION",
    "CAVEAT_CORE_DIR_UNRESOLVED",
    "CAVEAT_FIRMWARE_ROOT_MISSING",
    "CAVEAT_INFO_PATH_UNRESOLVED",
    "CAVEAT_NO_FIRMWARE_DECLARATION",
    "Caveat",
    "CoreInfo",
    "CoreOption",
    "STATE_MISMATCH",
    "STATE_MISSING",
    "STATE_PRESENT",
    "STATE_UNDECLARED",
    "STATE_VERIFIED",
    "FirmwareDeclaration",
    "FirmwareFile",
    "FirmwareHash",
    "FirmwareHashes",
    "FirmwareReport",
    "FirmwareState",
    "EMUDECK_DEFAULTS",
    "EmuDeck",
    "EmulatorEntry",
    "EmulatorSpec",
    "FileSet",
    "FixtureMachine",
    "HEALTH_ISSUE_COMPANION_CONFIG_MISSING",
    "HEALTH_ISSUE_CONFIG_UNREADABLE",
    "HEALTH_ISSUE_MARKER_INVALID",
    "HEALTH_ISSUE_MARKER_MISSING",
    "HEALTH_ISSUE_MARKER_UNREADABLE",
    "HEALTH_ISSUE_ROOT_MISSING",
    "HEALTH_ISSUE_SAVES_ROOT_MISSING",
    "Health",
    "Installation",
    "KIND_LIBRETRO",
    "KIND_STANDALONE",
    "LayoutDefaults",
    "Machine",
    "NativeRetroArch",
    "RETRODECK_DEFAULTS",
    "ROOT_CONTENT_DIRECTORY",
    "ROOT_SAVEFILE_DIRECTORY",
    "ROOT_SYSTEM_DIRECTORY",
    "RealMachine",
    "RetroArchCfg",
    "RetroDeck",
    "SavePlacement",
    "StandaloneRetroArchFlatpak",
    "UNKNOWN_FILE_SET",
    "UNRESOLVED_STANDALONE",
    "Unresolved",
    "UPSTREAM_DEFAULTS",
    "build_save_placement",
    "detect",
    "emulator_contract",
    "firmware_contract",
    "installation_contract",
    "placement_contract",
    "unresolved_contract",
    "interpret_cfg",
    "load_hashes",
    "read_declarations",
    "resolve_firmware",
    "parse_cfg_text",
    "parse_gamelist",
    "parse_gamelist_alternative",
    "resolve_save_layout",
]
